const HOST = "127.0.0.1"
const PORT = 3000

const DATA_PATH = "./src/cards.txt"
const RECORD_PATH = "./src/record.txt"

const NUMBER_OF_WORDS_PER_CARD = 5
const NUMBER_OF_CARDS_PER_GAME = 13
const NUMBER_OF_PLAYERS = 3

module.exports = { HOST, PORT, DATA_PATH, RECORD_PATH, NUMBER_OF_CARDS_PER_GAME, NUMBER_OF_PLAYERS, NUMBER_OF_WORDS_PER_CARD }